name: pyDevSup

# Trigger on pushes and PRs to any branch
on: [push, pull_request]

env:
    SETUP_PATH: .ci-local:.ci
    EPICS_TEST_IMPRECISE_TIMING: YES
    CMP: gcc
    BCFG: default

jobs:
  build-base:
    name: ${{ matrix.base }}/${{ matrix.os }}/${{ matrix.profile }}/${{ matrix.python }}/${{ matrix.extra }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    # Set environment variables from matrix parameters
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      PROF: ${{ matrix.profile }}
      EXTRA: ${{ matrix.extra }}
      TEST: ${{ matrix.test }}
      VV: "1"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.7"
            profile: deb10
            container: "python:3.7"
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.9"
            profile: deb11
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.11"
            profile: deb12
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.13"
            profile: deb13
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.6"
            container: "python:3.6"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.7"
            container: "python:3.7"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.8"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.9"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.10"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.11"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.12"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.13"
            profile: latest
            test: yes

          - os: macos-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            python: "3.10"
            profile: latest
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "3.15"
            python: "3.7"
            container: "python:3.7"
            profile: deb10
            test: yes

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "3.14"
            python: "3.7"
            container: "python:3.7"
            profile: deb10
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python }}
      if: ${{ !matrix.container }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: More Setup Python
      run: |
        python --version
        python -m pip --version
        python -m pip install --only-binary :all: -r requirements-${PROF}.txt
        cat <<EOF > configure/CONFIG_SITE.local
        PYTHON=$(which python)
        EOF
        echo === configure/CONFIG_SITE.local ===
        cat configure/CONFIG_SITE.local
    - name: Python sysconfig
      run: python -m sysconfig
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Build main module
      run: python .ci/cue.py build
    - name: Run main module tests
      if: matrix.test
      run: python .ci/cue.py build nose
